import { VestingScheme } from '@/types/vesting';

export const VESTING_SCHEMES: VestingScheme[] = [
  {
    id: 'accelerator',
    name: 'Pioneer',
    description: 'Give a big bonus upfront for maximum impact.',
    initialGrant: 0.02,
    employeeMatchPercentage: 0,
    icon: 'rocket',
    tagline: 'Maximum Impact',
    bestFor: 'Bold companies ready to lead',
    riskLevel: 'High',
    vestingSchedule: [
      {
        months: 0,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 0,
        description: 'No bonus earned yet',
      },
      {
        months: 60,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 50,
        description: '50% earned at 5 years',
      },
      {
        months: 120,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 100,
        description: '100% earned at 10 years',
      },
    ],
  },
  {
    id: 'steady-builder',
    name: 'Stacker',
    description: 'Smart starting bonus plus small yearly additions.',
    initialGrant: 0.015,
    employeeMatchPercentage: 0,
    annualGrant: 0.001,
    icon: 'chart-trending-up',
    tagline: 'Smart & Balanced',
    bestFor: 'Growing businesses',
    riskLevel: 'Medium',
    vestingSchedule: [
      {
        months: 0,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 0,
        description: 'Immediate access to contributions',
      },
      {
        months: 60,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 50,
        description: '50% vested at 5 years',
      },
      {
        months: 120,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 100,
        description: '100% vested at 10 years',
      },
    ],
  },
  {
    id: 'slow-burn',
    name: 'Builder',
    description: 'Small yearly bonuses keep costs low and predictable.',
    initialGrant: 0.002,
    employeeMatchPercentage: 0,
    annualGrant: 0.002,
    maxAnnualGrants: 9,
    icon: 'building-office',
    tagline: 'Low Cost',
    bestFor: 'Budget-conscious companies',
    riskLevel: 'Low',
    vestingSchedule: [
      {
        months: 0,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 0,
        description: 'Immediate access to contributions',
      },
      {
        months: 60,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 50,
        description: '50% vested at 5 years',
      },
      {
        months: 120,
        employeeContributionPercent: 100,
        employerContributionPercent: 0,
        grantPercent: 100,
        description: '100% vested at 10 years',
      },
    ],
  },
];


