# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    
    # Security updates configuration
    open-pull-requests-limit: 10
    target-branch: "main"
    
    # Versioning strategy
    versioning-strategy: "increase"
    
    # Group updates by type
    groups:
      # Group all patch-level updates
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      
      # Group minor updates for React ecosystem
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
          - "@testing-library/*"
        update-types:
          - "minor"
      
      # Group minor updates for build tools
      build-tools:
        patterns:
          - "next"
          - "typescript"
          - "eslint*"
          - "prettier*"
          - "@vitejs/*"
          - "vitest*"
          - "postcss*"
          - "tailwindcss*"
          - "autoprefixer"
        update-types:
          - "minor"
      
      # Group security updates (always prioritized)
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    
    # Ignore major version updates for stability
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "zod"
        update-types: ["version-update:semver-major"]
      - dependency-name: "recharts"
        update-types: ["version-update:semver-major"]
    
    # Commit message preferences
    commit-message:
      prefix: "security"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Pull request configuration
    reviewers:
      - "rathernotsay"
    assignees:
      - "rathernotsay"
    labels:
      - "dependencies"
      - "security"
    
    # Allow Dependabot to resolve conflicts
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    
    # Rebase strategy for clean history
    rebase-strategy: "auto"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "UTC"
    
    open-pull-requests-limit: 5
    target-branch: "main"
    
    commit-message:
      prefix: "ci"
      include: "scope"
    
    labels:
      - "github-actions"
      - "security"