[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--omit=dev"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"

# Performance optimized caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Preload key resources
[[headers]]
  for = "/"
  [headers.values]
    Link = '''</fonts/Inter-Regular.woff2>; rel=preload; as=font; type=font/woff2; crossorigin,
              </fonts/Inter-Medium.woff2>; rel=preload; as=font; type=font/woff2; crossorigin'''

# Redirect configuration for better SEO
[[redirects]]
  from = "/old-calculator/*"
  to = "/calculator/:splat"
  status = 301

[[redirects]]
  from = "/old-historical/*"  
  to = "/historical/:splat"
  status = 301
