[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = "--omit=dev"
  NODE_OPTIONS = "--max-old-space-size=6144"
  NEXT_TELEMETRY_DISABLED = "1"
  
# Build settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Performance optimized caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Redirect configuration for better SEO
[[redirects]]
  from = "/old-calculator/*"
  to = "/calculator/:splat"
  status = 301

[[redirects]]
  from = "/old-historical/*"  
  to = "/historical/:splat"
  status = 301