[build]
  command = "npm run build"
  # Remove publish directory to let @netlify/plugin-nextjs handle it
  # publish = ".next"

# Use Next.js runtime for proper asset serving
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.19.4"
  NPM_FLAGS = ""
  NODE_OPTIONS = "--max-old-space-size=6144"
  NEXT_TELEMETRY_DISABLED = "1"
  # Force cache refresh for react-dom types
  NETLIFY_CACHE_BUST = "2025-08-17-types-fix"
  
# Build settings
[build.processing]
  skip_processing = true

# Disable Netlify CSS/JS processing to prevent conflicts with Next.js
# Next.js already handles optimization, bundling, and minification
[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

# Performance optimized caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enhanced Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Clickjacking protection
    X-Frame-Options = "DENY"
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    # XSS protection for older browsers
    X-XSS-Protection = "1; mode=block"
    # Force HTTPS connections
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # Permissions Policy (replaces Feature-Policy)
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: blob:; font-src 'self' data:; connect-src 'self' https://api.coingecko.com https://mempool.space https://api.mempool.space; media-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests;"
    # DNS prefetch control
    X-DNS-Prefetch-Control = "on"
    # Prevent IE from executing downloads in site context
    X-Download-Options = "noopen"
    # Require same-origin for user activation
    X-Permitted-Cross-Domain-Policies = "none"

# Redirect configuration for better SEO
[[redirects]]
  from = "/old-calculator/*"
  to = "/calculator/:splat"
  status = 301

[[redirects]]
  from = "/old-historical/*"  
  to = "/historical/:splat"
  status = 301